### ISSUE TITLE
Appending RPATH linker flags with list(APPEND ...) generates a stray ";", breaking compilation

### ISSUE THREAD

**Issue by linedot** [ROCm/rocMLIR#687]
Hi all,
In `cmake/llvm-project.cmake` rpath flags are appended to `CMAKE_EXE_LINKER_FLAGS` with `list(APPEND ...`. This inserts a ";" between the previous flags (if present) and the newly appended flags, breaking compilation. This can be avoided by using `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ..."` to append the flags instead. I wrote a patch that's included here: https://github.com/rocm-arch/rocm-arch/pull/808

**Comment by krzysz00** [comment]
Does this need to be packported to the 5.2 branch?

**Comment by krzysz00** [comment]
@linedot (for the backport question)

**Comment by linedot** [comment]
Yes. I ran into the issue with 5.2.0 and am using the patch to get 5.2.0 compiling.

**Comment by krzysz00** [comment]
@jerryyin @mvermeulen What's the process here?

**Comment by jerryyin** [comment]
@krzysz00 @linedot In what way is it breaking the compilation and how come it is never a problem on our end of CI?

Using this result I need to evaluate how can our client MIOpen bump into this, because if we backport and if it is possible, it has to gone through MIOpen.

**Comment by krzysz00** [comment]
It probably never broke our CI because we never personally set the rpath to anything by hand, while it looks like this is a valid usecase externally

**Comment by jerryyin** [comment]
@krzysz00 That sounds right.

@linedot May I ask how what leads you to use rpath and `CMAKE_EXE_LINKER_FLAGS` after `ROCm 5.1.3`? I think this problem has exists for a while, do you have to do the same patch for releases in `ROCm 5.1.3` and before? 

Also, are you from AMD internal team working on this? I was more expecting the dev-op contact to let me of know of this so just curious.

**Comment by linedot** [comment]
Hi, I think there is some miscommunication. I'm not affiliated with AMD and I don't have the authority to tell if this needs to be ported to any branch. My answer was more to a question whether it affects 5.2.0.

I discovered the issue when looking into potentially building ROCm with EasyBuild, which definitely sets the variable and sees the issue (this work is not yet public). This also occurs with 5.1.3 (that's the version I started working with so I don't know about older versions). I also sometimes contribute to https://github.com/rocm-arch/rocm-arch and when putting the patch there was told to go to the source :D

**Comment by mvermeulen** [comment]
@linedot @krzysz00 @jerryyin 

Here is my suggestion.
1. First thanks for reporting this as well as confirming that it shows up for you on 5.2.0.  Also thanks for the patch.
2. In general, within AMD we'll fix this sort of thing for a future release, rather than backporting to re-release older releases.  So my suggestion is to apply this to the ROCm 5.3 release branch as well as main line.
3. In principle we could put it on our 5.2 branch so others building from source also don't see same issue - but I don't expect an update in ROCm 5.2 with this fix.

**Comment by jerryyin** [comment]
@linedot Thanks for the clarification and the context of everything. Also, we welcome patches/issues, so please feel free to continue to submit ticket/pull requests.

Exactly as @mvermeulen has pointed out: At this point, I think it is extremely hard to backport to pre-ROCm 5.2.0 branches because they are already in staging state. It may or may not be backported to ROCm 5.3 (ROCm 5.3.0) depends on how much our client team think this is necessary. But thanks to your contribution since this is already in our development branch, we are guaranteed to catch up on the next release.

**Comment by jerryyin** [comment]
Closing as fix is approved and merged by https://github.com/ROCmSoftwarePlatform/rocMLIR/pull/688
