### ISSUE TITLE
wrap the hip kernel [help wanted]

### ISSUE THREAD

**Issue by machoji** [ROCm/rocMLIR#721]
if my understanding is correct,  the workflow in this repo is : 
MIOpenDialect - GPU dialect - ROCDL dialect 

i'd like to use AMD GPU in different manner:
suppose that i already have a HIP kernel as below:
__global__ void
vectoradd_float(float* __restrict__ a, const float* __restrict__ b, const float* __restrict__ c, int width, int height)
  {
      int x = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
      int y = hipBlockDim_y * hipBlockIdx_y + hipThreadIdx_y;
 
      int i = y * width + x;
      if ( i < (width * height)) {
        a[i] = b[i] + c[i];
      } 
  }

1.  can this kernel be compiled individually
in OpenCL,  host code and device code can be compiled in different phase
when checking HIP programming,  host code and device code can be compiled together by using hipcc
now my question is,  can I compiler device kernel individually ?
if so,  what will it look like after compiling?

2.  is there way to wrap the kernel in MLIR?
seems that kernel outlining and gpu-to-cubin are same with my idea 
- but kernel outlining is based on gpu dialect
- gpu-to-cubin is for nvidia gpu
can anyone help to clarify how can i do for AMD GPU? 

many thanks

**Comment by krzysz00** [comment]
Ok so, while I'm not sure I entirely understand the question - I'll try and reply more thoroughly on Monday, but the AMD equivalent of gpu-to-cubin is gpu-to-rocdl

**Comment by krzysz00** [comment]
No, wait, wrong pass, the compiler is at `gpu-to-hsaco`

**Comment by krzysz00** [comment]
Ok, let me clarify: do you want to write HIP kernels in MLIR, or do you want to call a HIP kernel that you've already written in C++ from MLIR?

**Comment by machoji** [comment]
> Ok, let me clarify: do you want to write HIP kernels in MLIR, or do you want to call a HIP kernel that you've already written in C++ from MLIR?

thank you for answering. 
i'd like to call a HIP kernel that already been implemented.

I don't know how to compile HIP kernel by using MLIR
for example,  below is existing HIP kernel
`#include "hip/hip_runtime.h"
 
#define ARRAY_SIZE (16)
 
__device__ float myDeviceGlobal;
__device__ float myDeviceGlobalArray[16];
 
extern "C" __global__ void hello_world(const float* a, float* b) {
int tx = threadIdx.x;
b[tx] = a[tx];
}
 
extern "C" __global__ void test_globals(const float* a, float* b) {
int tx = threadIdx.x;
b[tx] = a[tx] + myDeviceGlobal + myDeviceGlobalArray[tx % ARRAY_SIZE];
}`

this kernel can be compiled by using 
`hipcc  --genco   vcpy_kernel.cpp -o vcpy_kernel.code`
how can we get same result by using MLIR ?


similar,  
below is host code to use the compiled kernel
`#include "hip/hip_runtime.h"
#include "hip/hip_runtime_api.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <hip/hip_ext.h>
 
#define LEN 64
#define SIZE LEN * sizeof(float)
 
#define fileName "vcpy_kernel.code"
 
int main() {
float *A, *B;
float *Ad, *Bd;
A = new float[LEN];
B = new float[LEN];
 
for (uint32_t i = 0; i < LEN; i++) {
A[i] = i * 1.0f;
B[i] = 0.0f;
}
 
hipInit(0);
hipDevice_t device;
hipCtx_t context;
hipDeviceGet(&device, 0);
hipCtxCreate(&context, 0, device);
 
hipMalloc((void**)&Ad, SIZE);
hipMalloc((void**)&Bd, SIZE);
 
hipMemcpyHtoD(hipDeviceptr_t(Ad), A, SIZE);
hipMemcpyHtoD((hipDeviceptr_t)(Bd), B, SIZE);
hipModule_t Module;
hipModuleLoad(&Module, fileName);
 
float myDeviceGlobal_h = 42.0;
float* deviceGlobal;
size_t deviceGlobalSize;
hipModuleGetGlobal((void**)&deviceGlobal, &deviceGlobalSize, Module, "myDeviceGlobal");
hipMemcpyHtoD(hipDeviceptr_t(deviceGlobal), &myDeviceGlobal_h, deviceGlobalSize);
 
#define ARRAY_SIZE 16
 
float myDeviceGlobalArray_h[ARRAY_SIZE];
float *myDeviceGlobalArray;
size_t myDeviceGlobalArraySize;
hipModuleGetGlobal((void**)&myDeviceGlobalArray, &myDeviceGlobalArraySize, Module, "myDeviceGlobalArray");
for (int i = 0; i < ARRAY_SIZE; i++) {
myDeviceGlobalArray_h[i] = i * 1000.0f;
hipMemcpyHtoD(hipDeviceptr_t(myDeviceGlobalArray), &myDeviceGlobalArray_h, myDeviceGlobalArraySize);
}
 
struct {
void* _Ad;
void* _Bd;
} args;
 
args._Ad = (void*) Ad;
args._Bd = (void*) Bd;
 
size_t size = sizeof(args);
 
void* config[] = {HIP_LAUNCH_PARAM_BUFFER_POINTER, &args, HIP_LAUNCH_PARAM_BUFFER_SIZE, &size,
HIP_LAUNCH_PARAM_END};
 
{
hipFunction_t Function;
hipModuleGetFunction(&Function, Module, "hello_world");
hipModuleLaunchKernel(Function, 1, 1, 1, LEN, 1, 1, 0, 0, NULL, (void**)&config);
 
hipMemcpyDtoH(B, Bd, SIZE);
 
int mismatchCount = 0;
for (uint32_t i = 0; i < LEN; i++) {
if (A[i] != B[i]) {
mismatchCount++;
std::cout << "error: mismatch " << A[i] << " != " << B[i] << std::endl;
if (mismatchCount >= 10) {
break;
}
}
}
 
if (mismatchCount == 0) {
std::cout << "PASSED!\n";
} else {
std::cout << "FAILED!\n";
};
}
 
{
hipFunction_t Function;
HIP_CHECK(hipModuleGetFunction(&Function, Module, "test_globals"));
int val =-1;
hipFuncGetAttribute(&val, HIP_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES,Function);
printf("Shared Size Bytes = %d\n",val);
hipFuncGetAttribute(&val, HIP_FUNC_ATTRIBUTE_NUM_REGS, Function);
printf("Num Regs = %d\n",val);
hipModuleLaunchKernel(Function, 1, 1, 1, LEN, 1, 1, 0, 0, NULL, (void**)&config);
 
hipMemcpyDtoH(B, Bd, SIZE);
 
int mismatchCount = 0;
for (uint32_t i = 0; i < LEN; i++) {
float expected = A[i] + myDeviceGlobal_h + myDeviceGlobalArray_h[i % 16];
if (expected != B[i]) {
mismatchCount++;
std::cout << "error: mismatch " << expected << " != " << B[i] << std::endl;
if (mismatchCount >= 10) {
break;
}
}
}
 
if (mismatchCount == 0) {
std::cout << "PASSED!\n";
} else {
std::cout << "FAILED!\n";
};
}
 
hipFree(Ad);
hipFree(Bd);
delete[] A;
delete[] B;
hipCtxDestroy(context);
return 0;
}`

how do we do this in MLIR way ?

**Comment by krzysz00** [comment]
Ok, so, there are two related questions here
- If you want to _compile_ a HIP kernel that you've expressed *in MLIR*, you need a `gpu.module` containing a `gpu.func` with the `kernel` attribute (though I think it might be `rocdl.kernel`, not sure right this second) on it containing the kernel code. Then, you want to run the pass `--gpu-to-rocdl='index-bitwidth=32'` (the index-bitwidth setting is optional but recommended) on it, followed by `--gpu-to-hsaco` to run the compiler
- The result of that will be creating a `gpu.module` op with a `gpu.binary` attribute on it. If you're trying to call code you've already compiled, you're looking to start around here. 
- In your circumstances, what you want to do is to take the contents of your `vcpy_kernel.code` file (not the name, the contents) and place it as a `gpu.binary` attribute on a `gpu.module`. Then, declare the `hello_world` function inside the `gpu.module` with a matching function signature and the `rocdl.kernel` attribute set.
- Most of your host code can be replaced with the corresponding ops in the `gpu` dialect. `gpu.alloc`, `gpu.memcpy`, and so on. These'll be lowered to calls to the HIP functions though an indirection layer
- Then, you "simply" run `--gpu-to-llvm` on the code, apply the other `-to-llvm` passes to your host code, and call `mlir-cpu-runner`, making sure to point at the HIP-based kernel execution widgets

The one thing we don't have is support for extracting constants from modules, since no one's needed it. You might want to write that.

BTW, you can get
```
a code block
```

with
\`\`\`
a code block
\`\`\`

**Comment by jerryyin** [comment]
Closing after one year of inactivity.
